/* Generated By:JavaCC: Do not edit this line. assignment_oneConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface assignment_oneConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int CONST = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int INTEGER = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int MAIN = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int SK = 23;
  /** RegularExpression Id. */
  int BEGIN = 24;
  /** RegularExpression Id. */
  int END = 25;
  /** RegularExpression Id. */
  int THEN = 26;
  /** RegularExpression Id. */
  int DO = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int COLON = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int LEFT_BRACE = 31;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 32;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 33;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 34;
  /** RegularExpression Id. */
  int ASSIGNMENT = 35;
  /** RegularExpression Id. */
  int PLUS = 36;
  /** RegularExpression Id. */
  int MINUS = 37;
  /** RegularExpression Id. */
  int NOT = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int AND = 40;
  /** RegularExpression Id. */
  int EQUALS = 41;
  /** RegularExpression Id. */
  int NOT_EQUALS = 42;
  /** RegularExpression Id. */
  int LESS_THAN = 43;
  /** RegularExpression Id. */
  int LESS_THAN_OR_EQUAL_TO = 44;
  /** RegularExpression Id. */
  int GREATER_THAN = 45;
  /** RegularExpression Id. */
  int GREATER_THAN_OR_EQUAL_TO = 46;
  /** RegularExpression Id. */
  int IDENTIFIER = 47;
  /** RegularExpression Id. */
  int CHAR = 48;
  /** RegularExpression Id. */
  int NUMBER = 49;
  /** RegularExpression Id. */
  int REAL = 50;
  /** RegularExpression Id. */
  int DIGIT = 51;
  /** RegularExpression Id. */
  int OTHER = 52;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\" \"",
    "<token of kind 6>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\"var\"",
    "\"const\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"skip\"",
    "\"begin\"",
    "\"end\"",
    "\"then\"",
    "\"do\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<IDENTIFIER>",
    "<CHAR>",
    "<NUMBER>",
    "<REAL>",
    "<DIGIT>",
    "<OTHER>",
  };

}
